title: Cfn-Sphere
email: marco_hoyer@gmx.de
description: > # this means to ignore newlines until "baseurl:"
   Cfn-Sphere helps you to run complex infrastructure on AWS managed with CloudFormation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cfn-sphere.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@Marco_Hoyer"
github_username:  marco-hoyer

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
